### ISSUE TITLE
Project non usable straight forward

### ISSUE THREAD

**Issue by mklkun** [arcivanov/pypi-cleanup#12]
After a basic `pip install pypi-cleanup` and a simple command:

```pypi-cleanup -u USER -p PROJECT -r r"*dev1$"```

I got this error message:
```Traceback (most recent call last):
  File "/Users/mkl/anaconda3/bin/pypi-cleanup", line 8, in <module>
    sys.exit(main())
  File "/Users/mkl/anaconda3/lib/python3.7/site-packages/pypi_cleanup/__init__.py", line 219, in main
    if args.patterns and not args.confirm and not args.dry_run:
AttributeError: 'Namespace' object has no attribute 'dry_run'```

**Comment by arcivanov** [comment]
Thanks, found and fixing it. Be advised that `r"*dev1$"` will not behave like you expect. You want `'*dev1$'`.

**Comment by mklkun** [comment]
Thank you for the fix and the comment. I will try this. :)
