### ISSUE TITLE
Login to pypi now requires to pass "I am Human" verification

### ISSUE THREAD

**Issue by gc-fu** [arcivanov/pypi-cleanup#27]
Hi, thanks for maintaining this great project!

Recently, while I am trying to use this tool, I encounter the error "Login for user failed".

I am wondering if this is due to the new added "I am human" verification?

![image](https://github.com/arcivanov/pypi-cleanup/assets/110874468/8ec27d27-5387-4347-ace6-0a1813e6b33a)

Any opinions on this, thanks!

**Comment by arcivanov** [comment]
Oh well, I guess it's all she wrote...
Yes, I'm 99.999% sure it's due to that.

**Comment by arcivanov** [comment]
The hCaptcha has been rolled back by PyPi. Hurray! Please verify that pypi-cleanup is functioning again and if so please close the issue. Thanks!

**Comment by gc-fu** [comment]
Thanks, I have verified that `pypi-cleanup==0.1.4` can be used normally.

For pypi-cleanup==0.1.5, I encounter this error:
```
File "/root/anaconda3/bin/pypi-cleanup", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 271, in main
    return PypiCleanup(**vars(args)).run()
  File "/root/anaconda3/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 83, in __init__
    self.date = datetime.datetime.now(datetime.UTC) - datetime.timedelta(days=days)
AttributeError: module 'datetime' has no attribute 'UTC'
```

But that's probably due to another issue, and not related to this anymore~

**Comment by arcivanov** [comment]
That's Python 3.8 problem unrelated to this, I guess. I'll spin it off into a different bug.
