### ISSUE TITLE
[Feature request] Send HTTP requests with an identifying user agent

### ISSUE THREAD

**Issue by woodruffw** [arcivanov/pypi-cleanup#34]
Hi there!

PyPI has seen some traffic from this tool, and it'd be valuable to signal the volume of that traffic using a custom user agent -- that will help inform the approach PyPI takes towards a deletion API for projects and releases.

If I understand correctly, this should be a pretty straightforward addition here:

https://github.com/arcivanov/pypi-cleanup/blob/e205f17872d6a3c0672608d65a9088b887f13c77/src/main/python/pypi_cleanup/__init__.py#L99

Something like `pypi-cleanup` as the user-agent would be ideal for PyPI's tracking purposes 🙂

**Comment by arcivanov** [comment]
I'll be happy to add that.

**Comment by arcivanov** [comment]
Would this work for you?

```
~$ nc -l 1234
GET /simple/pypi-cleanup/ HTTP/1.1
Host: localhost:1234
User-Agent: pypi-cleanup 0.1.7.dev20240624191147
Accept-Encoding: gzip, deflate, br, zstd
Accept: application/vnd.pypi.simple.v1+json
Connection: keep-alive

^C
```

**Comment by woodruffw** [comment]
That would be great, thank you! Including the `requests` version would also be slightly helpful, but not a huge deal if not included 🙂

**Comment by arcivanov** [comment]
Np, I'll add it

**Comment by arcivanov** [comment]
I'll adopt something like `pypi-cleanup/<version> (requests/<version>)` to be closer to the informal specs.

**Comment by arcivanov** [comment]
@woodruffw 
`User-Agent: pypi-cleanup/0.1.7.dev20240624220039 (requests/2.31.0)` good? anything else to add?

**Comment by woodruffw** [comment]
LGTM, thank you!
