### ISSUE TITLE
Bug / Cannot authenticate on Test PyPi with API Token

### ISSUE THREAD

**Issue by germainlefebvre4** [arcivanov/pypi-cleanup#40]
The authentication fails on Test PyPi with API Token

Here is my logs: https://github.com/germainlefebvre4/libtado/actions/runs/12110744039/job/33761618496?pr=427

**Comment by arcivanov** [comment]
You can't authenticate with the API token via PyPi GUI therefore pypi-cleanup is not able to authenticate using API token.
pypi-cleanup works by scraping the HTML webpage and pretending to be a browser to achieve the functionality. If there was an API capability that allowed us to support deleting releases there would be no need to this app in the first place.

**Comment by arcivanov** [comment]
@germainlefebvre4 try authenticating with the token in https://pypi.org/account/login/ and see if it works. I'm virtually certain that it won't. If it won't, pypi-cleanup will not be able to authenticate either.

**Comment by arcivanov** [comment]
@germainlefebvre4 bump

**Comment by germainlefebvre4** [comment]
You are right. Only human creds are processed.

I will pass my credentials, even though I am not confident nor at ease with this method.
